config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :pages do
      patch :translate, on: :member
    end
  end
  constraints(Spree::StaticPage) do
    get '/(*path)', :to => 'static_content#show', :as => 'static'
  end
end

app/models/spree/page.rb
class Spree::Page < Spree::Base
  default_scope -> { order("position ASC") }

  has_and_belongs_to_many :stores, :join_table => 'spree_pages_stores'

  validates_presence_of :title
  validates_presence_of [:slug, :body], :if => :not_using_foreign_link?
  validates_presence_of :layout, :if => :render_layout_as_partial?

  validates :slug, :uniqueness => true, :if => :not_using_foreign_link?
  validates :foreign_link, :uniqueness => true, :allow_blank => true

  scope :visible, -> { where(:visible => true) }
  scope :header_links, -> { where(:show_in_header => true).visible }
  scope :footer_links, -> { where(:show_in_footer => true).visible }
  scope :sidebar_links, -> { where(:show_in_sidebar => true).visible }

  scope :by_store, lambda { |store| joins(:stores).where("spree_pages_stores.store_id = ?", store) }

  before_save :update_positions_and_slug

  translates :title, :body, :slug, :layout, :foreign_link, :meta_keywords, :meta_title, :meta_description,
             fallbacks_for_empty_translations: true

  include SolidusGlobalize::Translatable

  def initialize(*args)
    super(*args)

    last_page = Spree::Page.last
    self.position = last_page ? last_page.position + 1 : 0
  end

  def link
    foreign_link.blank? ? slug : foreign_link
  end

private

  def update_positions_and_slug
    # ensure that all slugs start with a slash
    slug.prepend('/') if not_using_foreign_link? and not slug.start_with? '/'

    unless new_record?
      return unless prev_position = Spree::Page.find(self.id).position
      if prev_position > self.position
        Spree::Page.where("? <= position AND position < ?", self.position, prev_position).update_all("position = position + 1")
      elsif prev_position < self.position
        Spree::Page.where("? < position AND position <= ?", prev_position,  self.position).update_all("position = position - 1")
      end
    end

    true
  end

  def not_using_foreign_link?
    foreign_link.blank?
  end
end

app/controllers/spree/admin/pages_controller.rb
class Spree::Admin::PagesController < Spree::Admin::ResourceController
  def translate
    page = Spree::Page.find(params[:id])
    page.update update_page_attribute
    redirect_to spree.admin_pages_path
  end

  private
  def update_page_attribute
    params.require(:page).permit(permitted_params)
  end

  def permitted_params
    [:translations_attributes => [:id, :title, :body, :slug, :layout, :foreign_link, :meta_keywords, :meta_title, :meta_description]]
  end
  
end

app/controllers/spree/static_content_controller.rb
class Spree::StaticContentController < Spree::StoreController
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  
  helper 'spree/products'
  layout :determine_layout

  def show
    # @page = Spree::Page.by_store(current_store).visible.find_by_slug!(request.path)
    @page = Spree::Page.joins(:translations).by_store(current_store).visible.find_by!(slug: request.path)
  end

  private
    def determine_layout
      return @page.layout if @page and @page.layout.present? and not @page.render_layout_as_partial?
      Spree::Config.layout
    end

    def accurate_title
      @page ? (@page.meta_title.present? ? @page.meta_title : @page.title) : nil
    end
end

app/helpers/spree/pages_helper.rb
module Spree::PagesHelper
  def render_snippet(slug)
    page = Spree::Page.find_by(slug: slug)
    raw page.body if page
  end
end

app/views/spree/admin/pages/_form.html.erb
<div data-hook="admin_page_form_fields">
  <div class="left eight columns alpha" data-hook="admin_page_form_left">

    <%= f.field_container :title do %>
      <%= f.label :title %> <span class="required">*</span><br />
      <%= f.text_field :title, :class => 'fullwidth title' %>
      <%= f.error_message_on :title %>
    <% end %>

    <%= f.field_container :slug do %>
      <%= f.label :slug %> <span class="required">*</span><br />
      <%= f.text_field :slug, :class => 'fullwidth title' %>
      <%= f.error_message_on :slug %>
    <% end %>

    <%= f.field_container :body do %>
      <%= f.label :body %> <span class="required">*</span><br />
      <%= f.text_area :body, {rows: 12, :class => 'fullwidth'} %>
      <%= f.error_message_on :body %>
    <% end %>

  </div>
  <div class="right four columns omega" data-hook="admin_page_form_right">

    <%= f.field_container :layout do %>
      <%= f.label :layout %><br />
      <%= f.text_field :layout, :class => 'fullwidth title' %>
    <% end %>

    <%= f.field_container :foreign_link do %>
      <%= f.label :foreign_link %><br />
      <%= f.text_field :foreign_link, :class => 'fullwidth title' %>
    <% end %>

    <%= f.field_container :position do %>
      <%= f.label :position %><br />
      <%= f.number_field :position, :min => 0, :class => 'fullwidth title' %>
    <% end %>

    <%= f.field_container :show_in_sidebar do %>
      <%= f.check_box :show_in_sidebar %>
      <%= f.label :show_in_sidebar %>
    <% end %>

    <%= f.field_container :show_in_heade do %>
      <%= f.check_box :show_in_header %>
      <%= f.label :show_in_header %>
    <% end %>

    <%= f.field_container :show_in_footer do %>
      <%= f.check_box :show_in_footer %>
      <%= f.label :show_in_footer %>
    <% end %>

    <%= f.field_container :visible do %>
      <%= f.check_box :visible %>
      <%= f.label :visible %>
    <% end %>

    <%= f.field_container :render_layout_as_partial do %>
      <%= f.check_box :render_layout_as_partial %>
      <%= f.label :render_layout_as_partial %>
    <% end %>

    <%= f.field_container :stores do %>
      <%= f.label :stores, Spree.t(:stores)%><br />
      <% Spree::Store.all.each do |store| %>
        <%= check_box_tag "page[store_ids][]", store.id, @page.stores.include?(store) %> <%= store.name %>
      <% end %>
    <% end %>
    
  </div>

  <div data-hook="admin_page_form_meta" class="alpha omega twelve columns">

    <%= f.field_container :meta_title do %>
      <%= f.label :meta_title %><br />
      <%= f.text_field :meta_title, :class => 'fullwidth title' %>
      <%= f.error_message_on :meta_title %>
    <% end %>

    <%= f.field_container :meta_keywords do %>
      <%= f.label :meta_keywords %><br />
      <%= f.text_field :meta_keywords, :class => 'fullwidth title' %>
      <%= f.error_message_on :meta_keywords %>
    <% end %>

    <%= f.field_container :meta_description do %>
      <%= f.label :meta_description %><br />
      <%= f.text_field :meta_description, :class => 'fullwidth title' %>
      <%= f.error_message_on :meta_description %>
    <% end %>

  </div>
  <div class="clear"></div>
  <div data-hook="admin_page_form_additional_fields"></div>
  <div class="clear"></div>
</div>

app/views/spree/admin/pages/edit.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
   <%= Spree.t("static_content.static_pages") %> <i class="icon-arrow-right"></i> <%= Spree.t("static_content.editing_page") %> "<%= @page.title%>"
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_static_pages_list), spree.admin_pages_url %></li>
<% end %>

<%= render "spree/shared/error_messages", :target => @page %>

<%= form_for [:admin, @page] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/pages/index.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t("static_content.new_page"), new_object_url, id: 'admin_new_page' %></li>
<% end %>

<% content_for :page_title do %>
   <%= Spree.t("static_content.static_pages") %>
<% end %>

<% if @pages.any? %>
<table class="index responsive" id="listing_pages" data-hook>
  <colgroup>
    <col style="width: 35%">
    <col style="width: 30%">
    <col style="width: 10%">
    <col style="width: 10%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="admin_pages_index_headers">
      <th><%= Spree::Page.human_attribute_name(:title) %></th>
      <th><%= Spree.t("static_content.link") %></th>
      <th><%= Spree::Page.human_attribute_name(:visible) %></th>
      <th><%= Spree.t("static_content.is_partial") %></th>
      <th data-hook="admin_pages_index_header_actions" class="actions"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr data-hook="admin_pages_index_rows" class="<%= cycle('odd', 'even') %>" id="<%= dom_id page %>">
        <td>
          <%= page.title %>
        </td>
        <td>
          <%= link_to page.link, page.link, :target => '_blank' %>
        </td>
        <td class="align-center">
          <%= content_tag(:i, '', :class => 'fa fa-icon-ok green') if page.visible %>
        </td>
        <td class="align-center">
          <%= content_tag(:i, '', :class => 'fa fa-icon-ok green') if page.render_layout_as_partial %>
        </td>
        <td class="actions" data-hook="admin_pages_index_row_actions">
          <%= link_to_edit page, :no_text => true %>
          <%= link_to_delete page, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/page')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_page_path %>!
  </div>
<% end %>

app/views/spree/admin/pages/new.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
   <%= Spree.t("static_content.static_pages") %> <i class="icon-arrow-right"></i> <%= Spree.t("static_content.new_page") %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_static_pages_list), spree.admin_pages_url %></li>
<% end %>

<%= render "spree/shared/error_messages", :target => @page %>

<%= form_for [:admin, @page] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/translations/page.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_page) %> <span class="green">"<%= @page.title %>"</span>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_page_list), spree.admin_pages_path, :icon => 'icon-arrow-left' %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @page } %>

<div class="row">
  <fieldset class="no-border-top translations">

    <%= render 'settings' %>
    <%= form_for [:admin, @resource] do |f| %>

      <div class="row translations">
        <div class="col-md-8">
          <%= form_for [:admin, @resource] do |f| %>
            <%= render 'form_fields', f: f %>
            <%= render 'spree/admin/shared/edit_resource_links' %>
          <% end %>
        </div>
        <div class="col-md-4">
          <%= render 'fields' %>
        </div>
      </div>

    <% end %>
  </fieldset>
</div>

app/views/spree/static_content/_static_content_footer.html.erb
<nav id="footer-pages">
  <ul><%= render :partial => "spree/static_content/static_content_list", :collection => Spree::Page.by_store(current_store).visible.footer_links, :as => :page %></ul>
</nav>

app/views/spree/static_content/_static_content_header.html.erb
<%= render :partial => "spree/static_content/static_content_list", :collection => Spree::Page.by_store(current_store).visible.header_links, :as => :page %>

app/views/spree/static_content/_static_content_list.html.erb
<% if page.foreign_link.present? %>
  <li><%= link_to page.title, page.foreign_link, {:target => "_blank"} %></li>
<% else %>
  <% page_uri = Rails.application.routes.named_routes[:spree].path.spec.to_s == '/' ? page.slug : Rails.application.routes.named_routes[:spree].path.spec.to_s + page.slug %>
  <li class=<%= 'current' if (request.fullpath.gsub('//','/') == page_uri) %>><%= link_to page.title, page_uri  %></li>
<% end %>

app/views/spree/static_content/_static_content_sidebar.html.erb
<% if Spree::Page.by_store(current_store).visible.sidebar_links.any? %>
<nav id="pages" class="sidebar-item">
  <h6 class="pages-root"><%= Spree.t(:pages) %></h6>
  <ul class="pages-list"><%= render :partial => "spree/static_content/static_content_list", :collection => Spree::Page.visible.sidebar_links, :as => :page %></ul>
</nav>
<% end %>

app/views/spree/static_content/show.html.erb
<% if @page.layout.present? and @page.render_layout_as_partial? %>
  <%= render :partial => @page.layout %>
<% else %>
  <% content_for :head do -%>
    <%- if @page.meta_title.present? -%>
      <meta name="title" content="<%=@page.meta_title%>">
    <%- else -%>
      <meta name="title" content="<%=@page.title%>">
    <%- end -%>
    <meta name="keywords" content="<%=@page.meta_keywords%>">
    <meta name="description" content="<%=@page.meta_description%>">
  <% end -%>

  <% content_for :sidebar do %>
    <% if @products && @taxon %>
      <%= render :partial => "spree/shared/filters" %>
    <% elsif @taxonomies %>
      <%= render :partial => "spree/shared/taxonomies" %>
    <% end %>
  <% end %>

  <h1><%= @page.title %></h1>
  <div id="page_content">
    <%= raw @page.body %>
  </div>
<% end %>